### ISSUE TITLE
Can the tsmc40 process be replaced?

### ISSUE THREAD

**Issue by lhjey** [magical-eda/MAGICAL#44]
Hi, the layout of tsmc40nm pdk is used in the whole flow, so if post simulation is performed, the same pdk is required. Since I failed to find the tsmc40nm process, I would like to ask if I can change the tsmc40 to tsmc18 process in MAGICAL?

**Comment by krzhu** [comment]
Is tsmc18 180nm or 18nm? We currently cannot handle FinFET yet. 

We haven't really tried 180 too. I would say the placement and routing should probably be fine, but it needs modification on device generation. Basically it would require change on the templates of generating transistors, capacitors and etc. Otherwise the LVS tools cannot recognize the devices from the layouts. 

We currently don't have plan on supporting 180. I would suggest to contact us directly to have a high level discussion.

**Comment by lhjey** [comment]
OK，thanks. The tsmc18 I mentioned refers to 180nm. I will contact you by email to ask some questions.

**Comment by lhjey** [comment]
Hi, I found a version of tsmc40nm process ,but there is something wrong when I check DRC and XRC, LVS is correct. Can you tell me the version of tsmc40nm pdk used in MAGICAL? Thanks.

**Comment by AmrMohamedRashed** [comment]
@lhjey May you send me the link of tsmc40nm ?

**Comment by krzhu** [comment]
Due to NDA issue it's more suitable to contact Prof. David Pan for technology-related inqury. We use fake numbers for PDK information in the open release for TSMC technologies.
